services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    environment:
      - CLOUDFLARE_API_TOKEN_FILE=/run/secrets/ddns_cloudflare_api_key
      - DOMAINS=${DOMAINS}
      - PROXIED=false
      - IP6_PROVIDER=none
    secrets:
      - ddns_cloudflare_api_key

secrets:
  ddns_cloudflare_api_key:
    name: ${SECRET}
    external: true

